[project]
name = "github-data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nothingtosayy", email = "songala.rohith@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
github-data-pipeline = "github_data_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
